AppBundle\Entity\Panier:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PanierRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomProduit:
            type: string
            length: 255
            column: NomProduit
        quantite:
            type: integer
        prix:
            type: integer
    lifecycleCallbacks: {  }
